#!/bin/sh
# Test: restat rule generating a header cancels downstream rebuild via depfile
. "$(dirname "$0")/../test_helper.sh"

# header.h is generated by a restat rule.
# out.txt depends on header.h via depfile.
# If header.h doesn't change, out.txt should not rebuild.
cat > build.ninja <<'EOF'
rule gen_header
  command = echo static_header > $out.tmp && if cmp -s $out.tmp $out; then rm $out.tmp; else mv $out.tmp $out; fi
  restat = 1
rule cc
  command = cat $in > $out
  depfile = ${out}.d
  deps = gcc
build header.h: gen_header header.in
build out.txt: cc in.txt
EOF
echo "source" > in.txt
echo "data" > header.in

# First build
run_ninja
assert_exit_success
assert_file_exists header.h
assert_file_exists out.txt

# Create the depfile so ninja knows out.txt depends on header.h
echo "out.txt: header.h" > out.txt.d
run_ninja
assert_exit_success

# Save reference timestamps
cp -p out.txt out.txt.ref
sleep 1

# Touch header.in - gen_header reruns but produces same content,
# so out.txt should NOT be rebuilt
echo "different_input" > header.in
run_ninja
assert_exit_success
assert_file_not_newer out.txt out.txt.ref
